Friends/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.app_one.urls', namespace="app1")),
    url(r'^app2/', include('apps.app_two.urls', namespace="app2")),
    url(r'^admin/', admin.site.urls),
]

apps/app_one/urls.py
from django.conf.urls import url, include
from . import views

# This is app_one
urlpatterns = [
# root route to main method
    url(r'^$', views.index, name='index'),
    # url(r'^main$', views.index, name='main'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^logout$', views.logout, name='logout'),

]

apps/app_two/urls.py
#app-level url code:
from django.conf.urls import url, include
from . import views
from django.contrib import admin

urlpatterns = [
    url(r'^friends$', views.index, name='friends'),
    url(r'^add_friend/(?P<user2_id>\d+)$', views.add_friend, name='add_friend'),
    url(r'^remove_friend/(?P<friend_id>\d+)$', views.remove_friend, name='remove_friend'),
    url(r'^user/(?P<id>\d+)$', views.profile, name='profile'),

]

apps/app_two/models.py
from __future__ import unicode_literals
import re
from django.db import models
from datetime import datetime
from ..app_one.models import User, UserManager
import time
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')


class FriendManager(models.Manager):
    def add_friend(self, user_id, user2_id):
        print("This is addfriend in models.py")

# get object for logged-in user
        user = User.objects.get(id=user_id)
        print("user_id is:", user_id)

# get object for user selected to be new friend
        user2 = User.objects.get(id=user2_id)
        print("user2_id is:", user2_id)

# gets Friend objects by id of logged-in user, new friend user
# defines 2 lists
        friend_list = Friend.objects.get(user=User.objects.get(id=user_id))
        otheruser_list = Friend.objects.get(user = user2)

# uses related name to add new friend to logged-in user's friends list
        friend_list.friends.add(user2)
        print("other_user is:", user2.alias)
# uses related name to add logged-in user to new friend's list
        otheruser_list.friends.add(user)
        print("user is", user.alias)

# returns data to views.py
        return self


    def remove(self, user_id, friend_id):
        print("This is remove in models.py")
        user = User.objects.get(id = user_id)
        friend = User.objects.get(id = friend_id)

        users_list = Friend.objects.get(user=user)
        friends_list = Friend.objects.get(user=friend)

        friends_list.friends.remove(user)
        users_list.friends.remove(friend)
        return self



class Friend(models.Model):
    user = models.ForeignKey(User, related_name="has_friends")
    friends = models.ManyToManyField(User, related_name= "is_friends_with", default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __repr__(self):
        return "<FriendList object: {} {} {}>".format(self.user, self.id, self.friends)
    objects = FriendManager()

apps/app_two/views.py
from django.shortcuts import render, HttpResponse, redirect
from ..app_one.models import User, UserManager
from .models import Friend, FriendManager
# from apps.app_one.models import Friendship

# Create your views here.
def index(request):
    if 'user_id' not in request.session:
        return redirect('app1:main')
    else:
        print("This is index method in app2 views.py")
# get session user by id
        user_id = request.session['user_id']
        user = User.objects.get(id = user_id)

        friend_check = Friend.objects.get(user = user)
        print("Friend_list is:", friend_check, user)

        if friend_check.friends.count() == 0:
            print("No friends yet")
            request.session['no_friends'] = "You don't have friends yet"
        if friend_check.friends.count() > 0:
            print("no-friend list is blank")
            request.session['no_friends'] = ""

        allfriends = Friend.objects.get(user = User.objects.get(id=user_id))
        context = {

            # displays user's list of friends on friends page
            'friends': allfriends.friends.all(),
            'users': Friend.objects.all().exclude(user=user).exclude(friends=user),

        }

        return render(request, 'app_two/friends.html', context)


# user2_id sent in from Add Friend link in friends.html
def add_friend(request, user2_id):
    print("This is add_friend method in app2 views.py")
    print("ID of friend to add is:", user2_id)
    user_id = request.session['user_id']
    this_user = User.objects.get(id=user_id)
    print("User is", this_user.name)

# calls add_friend method in models.py, sends 2 ids
    addnewfriend = Friend.objects.add_friend(user_id, user2_id)

# returns to friends page
    return redirect('app2:friends')


# friend_id sent in from
def remove_friend(request, friend_id):
    print("This is remove_friend method in app2 views.py")
    user_id = request.session['user_id']
    removefriend = Friend.objects.remove(user_id, friend_id)


    return redirect('app2:friends')


def profile(request, id):
    print("This is profile method in app2 views.py")
    user = User.objects.get(id=id)
    context = {
    # each user by id
        'user': User.objects.get(id=id),
    }

    return render(request, 'app_two/user_profile.html', context)

apps/app_two/templates/app_two/friends.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app_two/css/style.css' %}" media="screen" title="no title">
    <title>Friends</title>
  </head>

  <body>
    <div class="wrapper">

      <div class="header">
        <p><h1>Hello, {{ request.session.user_alias }}!</h1><a href={% url 'app1:logout' %}>Logout</a></p>
      </div>

        <h3>Here is the list of your friends:</h3>

          <h4>{{ request.session.no_friends }}</h4>

          <br>
        <div class="friends_list">
          <table>
            <thead>
              <tr>
                <th>Alias</th>
                <th>Action</th>
              </tr>
            </thead>

            <tbody>
              {% for friend in friends %}
                <tr>
                  <td>{{ friend.alias }}</td>

                  <!-- needs right id route -->
                  <td><h5><a href="{% url 'app2:profile' id=friend.id %}">View profile</a></h5></td>
                  <!-- needs right id route -->
                    <td><h5 class = "friendlink"><a href="{% url 'app2:remove_friend' friend_id=friend.id %}">Remove as Friend</a></h5></td>


              {% endfor %}
            </tbody>
          </table>
        </div>


        <h3>Other users not on your friends list:</h3>

        <div class="others_list">
          <table>
            <thead>
              <tr>
                <th>Alias</th>
                <th>Action</th>
              </tr>
            </thead>

            <tbody>
              {% for user in users %}
                <tr>
                  <td><a href="{% url 'app2:profile' id=user.id %}">{{ user.user.alias }}</a></td>

                  <div class="buttonstyle">
                    <td><h5 class = "friendlink"><a href="{% url 'app2:add_friend' user2_id=user.user.id %}">Add as Friend</a></h5></td>

                  </div>


              {% endfor %}
            </tbody>

          </table>
        </div>

    </div> <!-- wrapper end div -->
  </body>
</html>

apps/app_two/templates/app_two/user_profile.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app_two/css/style.css' %}" media="screen" title="no title">
    <title>User profile</title>
  </head>
  <body>

    <div class="wrapper">
      <a href="{% url 'app2:friends' %}">Home</a>
      <a href="{% url 'app1:logout' %}">Logout</a>

      <h1>{{ user.alias }}'s Profile</h1>
      <h3>Name: {{ user.name }}</h3>
      <h3>Email Address: {{ user.email }}</h3>
    </div>

  </body>
</html>